CREATE TABLE ai_chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    user_message TEXT NOT NULL,
    ai_response JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    session_id UUID DEFAULT gen_random_uuid() NOT NULL
);

COMMENT ON COLUMN ai_chat_history.session_id IS 'A unique identifier for a single chat session.';

ALTER TABLE ai_chat_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own chat history"
ON ai_chat_history
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own chat history"
ON ai_chat_history
FOR INSERT
WITH CHECK (auth.uid() = user_id);
