{
  "openapi": "3.0.3",
  "info": {
    "title": "Secure API : LIVE Interactive Documentation",
    "description": "<div class=\"row pb-3\"> <div class=\"col-12\"> <div> <h5>This is LIVE Documentation that can connect directly to your account!</h5> <p>This LIVE Documentation can be directly accessed via the URL in your URL bar without logging in, which makes it possible for you to share this URL with your team or with your developer without giving full access to your account. However, no actual data can be accessed unless the LIVE Documentation is properly authorized with the Secure API Cr[...]"
  },
  "servers": [
    {
      "url": "https://app.suitedash.com/secure-api/"
    }
  ],
  "tags": [
    {
      "name": "contact",
      "description": "CRM Contacts : Available Endpoints"
    },
    {
      "name": "company",
      "description": "CRM Companies : Available Endpoints"
    },
    {
      "name": "project",
      "description": "Projects : Available Endpoints"
    },
    {
      "name": "marketing",
      "description": "Marketing : Available Endpoints"
    }
  ],
  "paths": {
    "/contact/meta": {
      "get": {
        "tags": [
          "contact"
        ],
        "summary": "CRM Contact : Meta Attributes Information",
        "description": "Contact meta attributes information<br><i><b><small>* dummy request allowed</small></b></i>",
        "operationId": "sorting02Contact1",
        "security": [
          {
            "Public-ID": ["read:contacts"],
            "Secret-Key": ["read:contacts"]
          }
        ]
      }
    },
    "/contacts": {
      "get": {
        "tags": [
          "contact"
        ],
        "summary": "Get all existing Contacts",
        "description": "Get all existing contacts<br><i><b><small>* dummy request allowed</small></b></i>",
        "operationId": "sorting02Contact2",
        "security": [
          {
            "Public-ID": ["write:contacts"],
            "Secret-Key": ["write:contacts"]
          }
        ]
      }
    },
    "/contact":{
      "post": {
        "tags": [
          "contact"
        ],
        "summary": "Create a new Contact",
        "description": "Create a new contact<br>Please use <b>/contact/meta</b> request for attributes full information",
        "operationId": "sorting02Contact4",
        "security": [
          {
            "Public-ID": ["write:contacts"],
            "Secret-Key": ["write:contacts"]
          }
        ]
      }
    },
    "/contact/{identifier}": {
      "get": {
        "tags": [
          "contact"
        ],
        "summary": "Find a Contact",
        "description": "Returns a single contact<br><i><b><small>* dummy request allowed</small></b></i>",
        "operationId": "sorting02Contact3",
        "security": [
          {
            "Public-ID": ["read:contacts"],
            "Secret-Key": ["read:contacts"]
          }
        ]
      },
      "put": {
        "tags": [
          "contact"
        ],
        "summary": "Update a Contact",
        "description": "Update a contact<br>Please use <b>/contact/meta</b> request for attributes full information",
        "operationId": "sorting02Contact5",
        "security": [
          {
            "Public-ID": ["write:contacts"],
            "Secret-Key": ["write:contacts"]
          }
        ]
      }
    },
    "/company/meta": {
      "get": {
        "tags": [
          "company"
        ],
        "summary": "CRM Company : Meta Attributes Information",
        "description": "Company meta attributes information<br><i><b><small>* dummy request allowed</small></b></i>",
        "operationId": "sorting01Company1",
        "security": [
          {
            "Public-ID": ["read:contacts"],
            "Secret-Key": ["read:contacts"]
          }
        ]
      }
    },
    "/companies": {
      "get": {
        "tags": [
          "company"
        ],
        "summary": "Get all existing Companies",
        "description": "Get all existing Companies (Idle Companies are not available)<br><i><b><small>* dummy request allowed</small></b></i>",
        "operationId": "sorting01Company2",
        "security": [
          {
            "Public-ID": ["write:contacts"],
            "Secret-Key": ["write:contacts"]
          }
        ]
      }
    },
  "/company":{
      "post": {
        "tags": [
          "company"
        ],
        "summary": "Create a new Company",
        "description": "Create a new company<br>Please use <b>/company/meta</b> request for attributes full information",
        "operationId": "sorting01Company4",
        "security": [
          {
            "Public-ID": ["write:companies"],
            "Secret-Key": ["write:companies"]
          }
        ]
      }
    },
    "/company/{identifier}": {
      "get": {
        "tags": [
          "company"
        ],
        "summary": "Find a Company",
        "description": "Returns a single company<br><i><b><small>* dummy request allowed</small></b></i>",
        "operationId": "sorting01Company3",
        "security": [
          {
            "Public-ID": ["read:contacts"],
            "Secret-Key": ["read:contacts"]
          }
        ]
      },
      "put": {
        "tags": [
          "company"
        ],
        "summary": "Update a Company",
        "description": "Update a company<br>Please use <b>/company/meta</b> request for attributes full information",
        "operationId": "sorting01Company5",
        "security": [
          {
            "Public-ID": ["write:contacts"],
            "Secret-Key": ["write:contacts"]
          }
        ]
      }
    },
    "/project/meta": {
      "get": {
        "tags": [
          "project"
        ],
        "summary": "Project : Meta Attributes Information",
        "description": "Project meta attributes information<br><i><b><small>* dummy request allowed</small></b></i>",
        "operationId": "sorting03Project1",
        "security": [
          {
            "Public-ID": ["read:contacts"],
            "Secret-Key": ["read:contacts"]
          }
        ]
      }
    },
    "/projects": {
      "get": {
        "tags": [
          "project"
        ],
        "summary": "Get all existing Projects",
        "description": "Get all existing Projects<br><i><b><small>* dummy request allowed</small></b></i>",
        "operationId": "sorting03Project2",
        "security": [
          {
            "Public-ID": ["write:project"],
            "Secret-Key": ["write:project"]
          }
        ]
      }
    },
    "/project/{type}/{identifier}": {
      "get": {
        "tags": [
          "project"
        ],
        "summary": "Find a Project",
        "description": "Returns a single Project<br><i><b><small>* dummy request allowed</small></b></i>",
        "operationId": "sorting03Project3",
        "security": [
          {
            "Public-ID": ["read:project"],
            "Secret-Key": ["read:project"]
          }
        ]
      },
      "put": {
        "tags": [
          "project"
        ],
        "summary": "Update a Project",
        "description": "Update a Project<br>Please use <b>/project/meta</b> request for attributes full information",
        "operationId": "sorting03Project4",
        "security": [
          {
            "Public-ID": ["write:project"],
            "Secret-Key": ["write:project"]
          }
        ]
      }
    },
    "/marketing/subscribe":{
      "post": {
        "tags": [
          "marketing"
        ],
        "summary": "Subscribe contacts to marketing audiences",
        "description": "Subscribe contacts to marketing audiences",
        "operationId": "sorting04Marketing1",
        "security": [
          {
            "Public-ID": ["write:contacts"],
            "Secret-Key": ["write:contacts"]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Public-ID": {
        "description": "The Public ID from the Secure API tab from Manage Account",
        "type": "apiKey",
        "in": "header",
        "name": "X-Public-ID"
      },
      "Secret-Key": {
        "description": "The Secret Key generated in the Secure API tab from Manage Account",
        "type": "apiKey",
        "in": "header",
        "name": "X-Secret-Key"
      }
    }
  }
}