import { supabase } from '../supabaseClient';
import config from '../../config';
import providerManager from './providerManager';
import { ApiKeyError, LLMProviderError } from './errors';

/**
 * Generates a mock response for development and testing purposes.
 * @param {string} prompt The input prompt.
 * @returns {Promise<string>} A promise that resolves with a mock response.
 */
async function getMockLlmResponse(prompt) {
  return new Promise(resolve => {
    setTimeout(() => {
      const response = `This is a mock response for the prompt: "${prompt}". The mock LLM is currently enabled.`;
      resolve(response);
    }, 500);
  });
}

/**
 * Generates content using the currently active LLM provider.
 * This function acts as the primary interface to the LLM backend,
 * abstracting away the specifics of which provider is being used.
 *
 * @param {string} prompt The prompt to send to the LLM.
 * @param {object} options Additional options for the LLM call (e.g., max_tokens).
 * @returns {Promise<string>} The content generated by the LLM.
 */
/**
 * Generates an embedding for the given input text.
 * @param {string} input The text to embed.
 * @returns {Promise<number[]>} A promise that resolves with the embedding vector.
 */
export const generateEmbedding = async (input) => {
  if (config.isMockLlmEnabled) {
    return Array(1536).fill(0);
  }

  if (!supabase) {
    throw new Error("Supabase client is not initialized.");
  }

  try {
    const { data, error } = await supabase.functions.invoke('generate-embedding', {
      body: { input },
    });

    if (error) {
      throw new Error(`Embedding Generation Error: ${error.message}`);
    }

    if (data.error) {
      throw new Error(`Embedding Generation Error: ${data.error}`);
    }

    return data.embedding;
  } catch (error) {
    console.error("Failed to generate embedding.", error);
    throw error;
  }
};

export const generateContent = async (prompt, options = {}) => {
  if (config.isMockLlmEnabled) {
    return getMockLlmResponse(prompt);
  }

  const availableProviders = providerManager.getAvailableProviders();
  let activeProviderName = providerManager.getActiveProviderName();

  if (!activeProviderName || !availableProviders.length) {
    throw new LLMProviderError("No LLM providers available. Please configure providers in the admin settings.");
  }

  if (!supabase) {
    throw new Error("Supabase client is not initialized.");
  }

  // Create a list of providers to try.
  // If options.provider is specified, prioritize it (and potentially only use it if we want to avoid fallback to others).
  // For now, if options.provider is set, we put it first.
  let providerQueue;
  if (options.provider) {
    // If a specific provider is requested (e.g. chatbase agent), we try that first.
    // We might want to avoid falling back to generic LLMs if the specific agent fails,
    // but for resilience, we'll keep the others as backup unless it's a very specific mismatch.
    // However, Chatbase requires specific params (chatbotId), so falling back to Gemini with those params might fail or be weird.
    // Let's assume if provider is forced, we ONLY try that provider to avoid confusion.
    providerQueue = [options.provider];
  } else {
    providerQueue = [
      activeProviderName,
      ...availableProviders.filter(p => p !== activeProviderName)
    ];
  }

  let lastError = null;

  for (const provider of providerQueue) {
    try {
      const { data, error } = await supabase.functions.invoke('llm-proxy', {
        body: { provider, prompt, options },
      });

      if (error) {
        throw new Error(`LLM Proxy Invocation Error: ${error.message}`);
      }

      if (data.error) {
        // Check if the error message from the proxy indicates an API key issue.
        if (typeof data.error === 'string' && data.error.toLowerCase().includes('api key')) {
          throw new ApiKeyError(data.error);
        }
        throw new LLMProviderError(data.error);
      }

      // If successful, update the active provider and return the content
      if (provider !== activeProviderName) {
        providerManager.setActiveProvider(provider);
      }
      return data.content;

    } catch (error) {
      lastError = error;
      console.warn(`Provider ${provider} failed: ${error.message}. Trying next provider.`);
    }
  }

  // If all providers failed
  console.error("All LLM providers failed.", lastError);
  throw new LLMProviderError(`Failed to get a response from any AI provider. Last error: ${lastError.message}`);
};

// Export the provider manager's methods for use in the UI
export const {
  loadProviders,
  getAvailableProviders,
  getActiveProviderName,
  setActiveProvider,
  getCurrentProvider,
  getActiveProviderUrl
} = providerManager;